### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/eliased-assembly-task-8#1]
**Very well done Elias!**

Your _Sieve of Eratosthenes_ is good! However, you might have missunderstood the _High-to-low_ task. You are supposed to implement two global routines `multiplication` and (with your naming) `realfactorial`. The trick to this is:
1) Declare the routines as global. _Hint_: search for the `globl` directive.
2) The register convensions say that argument registers (`$a0-$a3`) should be used to get input data by a routine, and the value registers (`$v0 & $v1`) should be used to return values from a routine.
3) The callee are expected to preserve the previous values of non-temporary registers, such as the return addess register (`$ra`) and the saved registers (`$s0-$s7`). This is done by pushing and poping to the stack before and after usage.
_Stack operation macros_:
```mips
##
# Push value to application stack.
# PARAM: Registry with value.
##
.macro	PUSH (%reg)
	addi	$sp,$sp,-4              # decrement stack pointer (stack builds "downwards" in memory)
	sw	    %reg,0($sp)             # save value to stack
.end_macro

##
# Pop value from application stack.
# PARAM: Registry which to save value to.
##
.macro	POP (%reg)
	lw	    %reg,0($sp)             # load value from stack to given registry
	addi	$sp,$sp,4               # increment stack pointer (stack builds "downwards" in memory)
.end_macro
```

The file can still hold a main routine for debugging purposes.

You have the arithmetic logic already, now only the formalities has to be completed. See other student solutions and assignment instruction examples for help.

Good luck!

**Comment by MazeofIth** [comment]
Har kompletterat nu

**Comment by MazeofIth** [comment]
På java-uppgiften (8) också

**Comment by violaso** [comment]
Thanks! Good job!
